# Generated by Django 5.0.1 on 2024-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="https://picsum.photos/200/200",
                max_length=255,
                null=True,
            ),
        ),
    ]
