# Generated by Django 5.0.1 on 2024-01-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
