# Generated by Django 5.0.1 on 2024-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.IntegerField()),
                ("display_name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("cover_image", models.URLField()),
                ("reviews_count", models.IntegerField()),
                ("tags_desc", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("review_rating", models.FloatField()),
                ("feature_reviews", models.TextField()),
            ],
            options={
                "verbose_name": "tours",
            },
        ),
    ]
